I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script
    image hiyori = Live2D("images/hiyori_pro_t11",base=.6, aliases={"idle" : "m01"})
  File "game/script.rpy", line 7, in <module>
    image hiyori = Live2D("images/hiyori_pro_t11",base=.6, aliases={"idle" : "m01"})
Exception: Name 'm01' is not a known motion or expression.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script
    image hiyori = Live2D("images/hiyori_pro_t11",base=.6, aliases={"idle" : "m01"})
  File "D:\Games\renpy-8.1.3-sdk\renpy\ast.py", line 922, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\Games\renpy-8.1.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 7, in <module>
    image hiyori = Live2D("images/hiyori_pro_t11",base=.6, aliases={"idle" : "m01"})
  File "D:\Games\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 581, in __init__
    common.apply_aliases(aliases)
  File "D:\Games\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 356, in apply_aliases
    raise Exception("Name {!r} is not a known motion or expression.".format(v))
Exception: Name 'm01' is not a known motion or expression.

Windows-10-10.0.19041 AMD64
Ren'Py 8.2.0.24012702
Code D 1.0
Mon Feb  5 15:04:21 2024
