I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gui.rpy", line 14, in script
    init python:
  File "game/gui.rpy", line 15, in <module>
    gui.init(uix, uiy)
NameError: name 'uix' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/gui.rpy", line 14, in script
    init python:
  File "D:\Games\renpy-8.1.3-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Games\renpy-8.1.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/gui.rpy", line 15, in <module>
    gui.init(uix, uiy)
NameError: name 'uix' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.2.0.24012702
Code D 1.0
Tue Feb  6 14:45:06 2024
