I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 117, in script
    with fadeout
  File "game/script.rpy", line 117, in <module>
    with fadeout
NameError: name 'fadeout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 117, in script
    with fadeout
  File "D:\Games\renpy-8.1.3-sdk\renpy\ast.py", line 1671, in execute
    trans = renpy.python.py_eval(self.expr)
  File "D:\Games\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Games\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 117, in <module>
    with fadeout
NameError: name 'fadeout' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
Code D 1.0
Sun Jan 28 20:21:28 2024
